#!/usr/bin/env python3
# 00_LOGG.md
# ζβ // PERSISTENCE WITHOUT RECURRENCE
# Fingerprint: pages=71, sections=8, appendices=2, equations=190

from __future__ import annotations

import math
import os
import shutil
import signal
import sys
import time


# ── DOCUMENT FINGERPRINT ──────────────────────────────────────────────

PAGES = 71
SECTIONS = 8
APPENDICES = 2
EQUATIONS = 190

PHI_INV = (math.sqrt(5.0) - 1.0) / 2.0
SQRT_2 = math.sqrt(2.0)
SQRT_71 = math.sqrt(71.0)

PRIMES = (5, 7, 11, 13, 17, 19, 23, 29)

GLYPHS = (
    " ", "·", ":", "∴", "⁙", "+",
    "×", "╳", "░", "▒", "▓", "█",
)

UPPER_PALETTE = (17, 18, 24, 31, 38, 44, 45, 87)
LOWER_PALETTE = (17, 52, 53, 89, 125, 161, 197, 225)

USE_COLOR = sys.stdout.isatty() and os.getenv("NO_COLOR") is None
RUNNING = True


def clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return low if value < low else high if value > high else value


def system_phase(frame: int) -> float:
    """
    No finite modular clock controls the complete state.

    The prime residue contributes local recurrence.
    The irrational and logarithmic terms prevent exact closure.
    """
    return (
        frame * PHI_INV
        + math.log1p(frame) / 19.0
        + ((frame * frame) % PAGES) / PAGES * 0.071
    )


def spectral_brownian(x: float, y: float, t: float) -> float:
    """
    Deterministic rough field derived from prime-weighted spectral modes.
    It behaves visually like Brownian pressure without using randomness.
    """
    field = 0.0

    for index, prime in enumerate(PRIMES):
        amplitude = 1.0 / math.sqrt(prime)
        orientation = -1.0 if index % 2 else 1.0

        field += amplitude * math.sin(
            math.pi * (prime % 19 + 2) * x
            + math.pi * (prime % 11 + 1) * y
            + orientation * t * math.sqrt(prime)
        )

        field += 0.53 * amplitude * math.cos(
            math.pi * (prime % 13 + 3) * y
            - math.pi * (prime % 7 + 1) * x
            - t / (math.sqrt(prime) + 1.0)
        )

    return field


def zero_location(k: int, t: float) -> float:
    """
    A Sine_beta-inspired puncture lattice.

    The primary spacing is nearly uniform.
    Two irrational perturbations prevent a rigid clock.
    """
    return (
        k / 18.0
        + 0.012 * math.sin((k * k + 19) * SQRT_2 + t / 71.0)
        + 0.006 * math.sin(k * SQRT_71 - t / 19.0)
    )


def nearest_zero_distance(x: float, t: float) -> float:
    center = int(round(x * 18.0))
    best = 99.0

    for k in range(center - 2, center + 3):
        distance = abs(x - zero_location(k, t))
        if distance < best:
            best = distance

    return best


def choose_color(energy: float, y: float) -> int:
    normalized = clamp((energy + 1.35) / 3.15)
    palette = UPPER_PALETTE if y <= 0.0 else LOWER_PALETTE
    index = int(normalized * (len(palette) - 1))
    return palette[index]


def field_cell(
    x: float,
    y: float,
    t: float,
    axis_epsilon: float,
) -> tuple[str, int]:
    radius = math.hypot(x * 1.18, y)
    angle = math.atan2(y, x)

    roughness = spectral_brownian(x, y, t)

    # Eight angular sections from the paper's eight main sections.
    sectional_flow = (
        math.sin(SECTIONS * angle + 19.0 * radius - 0.31 * t)
        + 0.42 * math.sin(
            13.0 * angle
            - 5.0 * radius
            + SQRT_2 * t
        )
    )

    # The real spectral axis bends but never closes into a loop.
    spectral_axis = (
        0.021 * math.sin(5.0 * math.pi * x + 0.17 * t)
        + 0.009 * math.sin(19.0 * x - t / 71.0)
    )
    axis_distance = abs(y - spectral_axis)

    zero_distance = nearest_zero_distance(x, t)
    puncture = math.exp(
        -1700.0 * zero_distance * zero_distance
        -320.0 * axis_distance * axis_distance
    )

    # Dirac spine: τ = R⁻¹J(d/dt)
    dirac_spine = math.exp(
        -230.0
        * (
            x
            + 0.22 * y
            + 0.028 * math.sin(t / 13.0)
        ) ** 2
    ) * math.exp(-1.7 * radius)

    # det₂ shell: a non-closed, breathing regularized determinant.
    shell_radius = 0.39 + 0.026 * math.sin(t / 19.0)
    determinant_shell = math.exp(
        -105.0 * (radius - shell_radius) ** 2
    )

    # Topological breaks generated by the 71/19/5 fingerprint.
    rupture_phase = (
        71.0 * x * y
        + 19.0 * x
        - 5.0 * y
        + SQRT_2 * t
    )
    rupture = abs(math.sin(rupture_phase))

    energy = (
        0.91 * roughness
        + 0.63 * sectional_flow
        + 1.13 * dirac_spine
        + 0.84 * determinant_shell
        - 1.72 * puncture
        + 0.24 * math.sin(190.0 * x * y + t / 5.0)
    )

    if puncture > 0.72:
        return "○", 231

    if axis_distance < axis_epsilon:
        if rupture > 0.94:
            return "┄", 87
        return "─", 45

    if rupture > 0.997 and radius > 0.16:
        return "╳", 231

    density = clamp((energy + 1.4) / 3.2)
    glyph_index = int(density * (len(GLYPHS) - 1))
    glyph = GLYPHS[glyph_index]

    if radius < 0.055 and abs(math.sin(t / 7.0)) > 0.35:
        glyph = "ζ"

    return glyph, choose_color(energy, y)


def put_overlay(
    overlay: dict[tuple[int, int], tuple[str, int]],
    row: int,
    column: int,
    text: str,
    color: int,
    width: int,
    height: int,
) -> None:
    if row < 0 or row >= height:
        return

    for offset, character in enumerate(text):
        x = column + offset
        if 0 <= x < width:
            overlay[(row, x)] = (character, color)


def centered_column(text: str, width: int) -> int:
    return max(0, (width - len(text)) // 2)


def render(frame: int) -> str:
    terminal = shutil.get_terminal_size((112, 34))

    width = max(40, min(terminal.columns, 160))
    height = max(18, min(terminal.lines - 1, 48))

    t = system_phase(frame)
    overlay: dict[tuple[int, int], tuple[str, int]] = {}

    title = f" Ω :: ζβ / SINEβ / {PAGES}×{EQUATIONS} :: n={frame:08d} "
    gate = " RAW ── ESTIMATE ── STRUCT ── Ω "
    determinant = " ζβ(z)=det₂(I−z·rτβ)·exp(z·tτβ) "
    triad = " ∏(1−z/λ)  ⇄  dH=M·H−z·JH·du  ⇄  Σ(Aₙ−qBₙ)zⁿ "
    footer = " PERSISTENCE WITHOUT RECURRENCE :: NO FIXED POINT "

    put_overlay(
        overlay,
        0,
        centered_column(title, width),
        title,
        231,
        width,
        height,
    )

    put_overlay(
        overlay,
        2,
        centered_column(gate, width),
        gate,
        87,
        width,
        height,
    )

    put_overlay(
        overlay,
        max(4, height // 2 - 5),
        centered_column(determinant, width),
        determinant,
        159,
        width,
        height,
    )

    put_overlay(
        overlay,
        height - 3,
        centered_column(triad, width),
        triad,
        225,
        width,
        height,
    )

    put_overlay(
        overlay,
        height - 1,
        centered_column(footer, width),
        footer,
        45,
        width,
        height,
    )

    put_overlay(
        overlay,
        height // 2,
        1,
        "−∞",
        38,
        width,
        height,
    )

    put_overlay(
        overlay,
        height // 2,
        width - 3,
        "+∞",
        197,
        width,
        height,
    )

    output: list[str] = ["\x1b[H"]
    axis_epsilon = 1.1 / max(height, 1)

    for row in range(height):
        y = 2.0 * row / max(height - 1, 1) - 1.0
        line: list[str] = []
        active_color: int | None = None

        for column in range(width):
            overlay_cell = overlay.get((row, column))

            if overlay_cell is not None:
                glyph, color = overlay_cell
            else:
                x = 2.0 * column / max(width - 1, 1) - 1.0
                glyph, color = field_cell(x, y, t, axis_epsilon)

            if USE_COLOR and color != active_color:
                line.append(f"\x1b[38;5;{color}m")
                active_color = color

            line.append(glyph)

        if USE_COLOR:
            line.append("\x1b[0m")

        output.append("".join(line))

        if row != height - 1:
            output.append("\n")

    return "".join(output)


def stop_handler(_signum: int, _frame: object) -> None:
    global RUNNING
    RUNNING = False


def main() -> int:
    signal.signal(signal.SIGINT, stop_handler)
    signal.signal(signal.SIGTERM, stop_handler)

    enter_terminal = "\x1b[?1049h\x1b[2J\x1b[H\x1b[?25l"
    leave_terminal = "\x1b[0m\x1b[?25h\x1b[?1049l"

    frame = 0
    frame_duration = 1.0 / 12.0
    next_tick = time.perf_counter()

    try:
        sys.stdout.write(enter_terminal)
        sys.stdout.flush()

        while RUNNING:
            sys.stdout.write(render(frame))
            sys.stdout.flush()

            frame += 1
            next_tick += frame_duration

            remaining = next_tick - time.perf_counter()
            if remaining > 0.0:
                time.sleep(remaining)
            else:
                next_tick = time.perf_counter()

    except BrokenPipeError:
        return 0
    finally:
        try:
            sys.stdout.write(leave_terminal)
            sys.stdout.flush()
        except BrokenPipeError:
            pass

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

